import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex items-center justify-center gap-8 p-4 bg-gray-800 text-white">
          <a href="/" className="text-white">
            Home
          </a>
          <a href="/profile" className="text-white">
            profile
          </a>
        
        </nav>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
